const data = [
    [
      '2022-06-01',
      'PUR001',
      'example1@example.com',
      'John Doe',
      'Website',
      'Paid',
      "Select",
    ],
    [
      '2022-06-02',
      'PUR002',
      'example2@example.com',
      'Jane Smith',
      'App',
      'Failed',
      "Select",
    ],
    [
      '2022-06-03',
      'PUR003',
      'example3@example.com',
      'Michael Johnson',
      'Website',
      'Waiting',
      "Select",
    ],
    [
      '2022-06-04',
      'PUR004',
      'example4@example.com',
      'Sarah Wilson',
      'App',
      'Paid',
      "Select",
    ],
    [
      '2022-06-05',
      'PUR005',
      'example5@example.com',
      'David Brown',
      'Website',
      'Waiting',
      "Select",
    ],
    [
      '2022-06-06',
      'PUR006',
      'example6@example.com',
      'Emily Davis',
      'App',
      'Paid',
      "Select",
    ],
    [
      '2022-06-07',
      'PUR007',
      'example7@example.com',
      'Andrew Johnson',
      'Website',
      'Waiting',
      "Select",
    ],
    [
      '2022-06-08',
      'PUR008',
      'example8@example.com',
      'Sophia Wilson',
      'App',
      'Paid',
      "Select",
    ],
    [
      '2022-06-09',
      'PUR009',
      'example9@example.com',
      'James Smith',
      'Website',
      'Waiting',
      "Select",
    ],
    [
      '2022-06-10',
      'PUR010',
      'example10@example.com',
      'Olivia Johnson',
      'App',
      'Paid',
      "Select",
    ],
    [
      '2022-06-11',
      'PUR011',
      'example11@example.com',
      'Benjamin Davis',
      'Website',
      'Waiting',
      "Select",
    ],
    [
      '2022-06-12',
      'PUR012',
      'example12@example.com',
      'Sophia Brown',
      'App',
      'Paid',
      "Select",
    ],
    [
      '2022-06-13',
      'PUR013',
      'example13@example.com',
      'William Wilson',
      'Website',
      'Waiting',
      "Select",
    ],
    [
      '2022-06-14',
      'PUR014',
      'example14@example.com',
      'Ava Smith',
      'App',
      'Paid',
      "Select",
    ],
    [
      '2022-06-15',
      'PUR015',
      'example15@example.com',
      'Emma Johnson',
      'Website',
      'Waiting',
      "Select",
    ],
    [
      '2022-06-16',
      'PUR016',
      'example16@example.com',
      'Noah Davis',
      'App',
      'Paid',
      "Select",
    ],
    [
      '2022-06-17',
      'PUR017',
      'example17@example.com',
      'Mia Wilson',
      'Website',
      'Waiting',
      "Select",
    ],
    [
      '2022-06-18',
      'PUR018',
      'example18@example.com',
      'Liam Smith',
      'App',
      'Paid',
      "Select",
    ],
    [
      '2022-06-19',
      'PUR019',
      'example19@example.com',
      'Isabella Johnson',
      'Website',
      'Waiting',
      "Select",
    ],
    [
      '2022-06-20',
      'PUR020',
      'example20@example.com',
      'Lucas Davis',
      'App',
      'Paid',
      "Select",
    ],
    [
      '2022-06-21',
      'PUR021',
      'example21@example.com',
      'Grace Wilson',
      'Website',
      'Waiting',
      "Select",
    ],
    [
      '2022-06-22',
      'PUR022',
      'example22@example.com',
      'Jackson Smith',
      'App',
      'Paid',
      "Select",
    ],
    [
      '2022-06-23',
      'PUR023',
      'example23@example.com',
      'Charlotte Johnson',
      'Website',
      'Waiting',
      "Select",
    ],
    [
      '2022-06-24',
      'PUR024',
      'example24@example.com',
      'Ethan Davis',
      'App',
      'Paid',
      "Select",
    ],
    [
      '2022-06-25',
      'PUR025',
      'example25@example.com',
      'Avery Wilson',
      'Website',
      'Waiting',
      "Select",
    ],
  ];
  
  export default data;
  